import "./globals.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ConvexClientProvider from "./ConvexClientProvider";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Todo Next App",
	description: "Generated by create next app",
	icons: "/book.svg",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`bg-gray-900 ${poppins.className}`}>
				<ConvexClientProvider>{children}</ConvexClientProvider>
			</body>
		</html>
	);
}
